# Generated by Django 3.2.9 on 2022-10-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=10000)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('qntd_livro', models.IntegerField(default=0)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
